### ISSUE TITLE
Unable to test early finalization prevention

### ISSUE THREAD

**Issue by jacob-hughes** [softdevteam/alloy#45]
Early finalization prevention is done with the `prevent_early_finalization` MIR transformation. It's not possible to test this with a mir-opt test because diffing MIR generated from the alloc crate leads to different output on different architectures. The crate hash for `alloc::Gc` is pulled in and that changes depending on which machine compiles the test. Although this isn't necessary to show that early finalization was prevented, right now there's no way to use a wildcard for this particular output when comparing the diffs.

**Comment by ltratt** [comment]
I think we can close this issue?
